config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/upload", views.UploadPhotoView.as_view(), name="upload"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.search, name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
]

templates/partials/footer.html
<footer class="side-padding absolute bottom-0 container h-40 bg-gray-200 flex flex-col items-center justify-center text-gray-400">

    <i class="fa-brands fa-airbnb fa-2xl mb-5"></i>
    <span>&copy; 2022 Nomad Coders. All rights reserved.</span>
    
</footer>

templates/partials/header.html
<header class="side-padding container max-w-full flex h-20 items-center justify-between border-b border-gray-300 shadow-md fixed inset-0 z-10 bg-white">
    <div class="w-1/3 flex justify-start">
        <a href="{% url 'core:home' %}">
            <i class="fa-brands fa-airbnb font-black text-5xl text-airbnb-pink"></i>
        </a>
    </div>
    <div class="w-1/3 flex justify-center">
    {% block search_bar %}
        <form class="w-full" action="{% url 'rooms:search' %}">
            <input class="border w-full pl-6 pr-24 py-3 shadow-md hover:shadow-lg transition-shadow text-sm font-bold placeholder-gray-500 focus:outline-none" type="text" name="city" placeholder="Search by City">
        </form>
    {% endblock search_bar %}
    </div>
    <div class="w-1/3 flex justify-end">
        {% include 'partials/navigation.html' %}
    </div>
</header>

templates/partials/messages.html
{% if messages %}
<ul class="bg-red-700">
    {% for message in messages %}
    <li class="fixed z-20 top-0 left-0 right-0 mx-auto text-center message px-10 py-2 rounded-full font-bold text-lg text-white {% if message.tags %}{{ message.tags }}{% endif %}">
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/navigation.html
<nav>
    <ul class="flex font-bold text-sm">
        <li class="ml-6 hover:text-airbnb-pink"><a href="{% url 'rooms:search' %}">Search</a></li>
        {% if user.is_authenticated %}
        <li class="ml-6 hover:text-airbnb-pink"><a href="{% url 'rooms:create' %}">Create Room</a></li>
        <li class="ml-6 hover:text-airbnb-pink"><a href="{{user.get_absolute_url}}">Profile</a></li>
        <li class="ml-6 hover:text-airbnb-pink"><a href="{% url 'users:logout' %}">Log Out</a></li>
        {% else %}
        <li class="ml-6 hover:text-airbnb-pink"><a href="{% url 'users:signup' %}">Sign Up</a></li>
        <li class="ml-6 hover:text-airbnb-pink"><a href="{% url 'users:login' %}">Log In</a></li>
        {% endif %}
    </ul>
</nav>

templates/partials/pagination.html
<div class="mt-20 mx-auto flex justify-center items-center">
    
    {% if page_obj.has_previous %}
        <a href="?p={{page_obj.previous_page_number}}">
            <i class="fa-solid fa-circle-chevron-left fa-lg text-airbnb-green"></i>
        </a>
    {% endif %}
        
    <span class="mx-3 font-bold text-lg">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>
    
    {% if page_obj.has_next %}
        <a href="?p={{page_obj.next_page_number}}">
            <i class="fa-solid fa-circle-chevron-right fa-lg text-airbnb-green"></i>
        </a>
    {% endif %}
        
</div>

templates/partials/social_login.html
<div class="flex flex-col items-center w-72">
    <a class="btn border-2 border-github-gray mb-1 text-github-gray" href="{% url 'users:github-login' %}">
        <svg class="w-5 mr-2" style="fill-github-gray;" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>
        </svg>
        <span>Continue with GitHub</span>
    </a>
    <a class="btn bg-kakao-yellow" href="{% url 'users:kakao-login' %}">
        <svg class="w-5 mr-2" style="" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="M22.125 0H1.875C.8394 0 0 .8394 0 1.875v20.25C0 23.1606.8394 24 1.875 24h20.25C23.1606 24 24 23.1606 24 22.125V1.875C24 .8394 23.1606 0 22.125 0zM12 18.75c-.591 0-1.1697-.0413-1.7317-.1209-.5626.3965-3.813 2.6797-4.1198 2.7225 0 0-.1258.0489-.2328-.0141s-.0876-.2282-.0876-.2282c.0322-.2198.8426-3.0183.992-3.5333-2.7452-1.36-4.5701-3.7686-4.5701-6.5135C2.25 6.8168 6.6152 3.375 12 3.375s9.75 3.4418 9.75 7.6875c0 4.2457-4.3652 7.6875-9.75 7.6875zM8.0496 9.8672h-.8777v3.3417c0 .2963-.2523.5372-.5625.5372s-.5625-.2409-.5625-.5372V9.8672h-.8777c-.3044 0-.552-.2471-.552-.5508s.2477-.5508.552-.5508h2.8804c.3044 0 .552.2471.552.5508s-.2477.5508-.552.5508zm10.9879 2.9566a.558.558 0 0 1 .108.4167.5588.5588 0 0 1-.2183.371.5572.5572 0 0 1-.3383.1135.558.558 0 0 1-.4493-.2236l-1.3192-1.7479-.1952.1952v1.2273a.5635.5635 0 0 1-.5627.5628.563.563 0 0 1-.5625-.5625V9.3281c0-.3102.2523-.5625.5625-.5625s.5625.2523.5625.5625v1.209l1.5694-1.5694c.0807-.0807.1916-.1252.312-.1252.1404 0 .2814.0606.3871.1661.0985.0984.1573.2251.1654.3566.0082.1327-.036.2542-.1241.3425l-1.2818 1.2817 1.3845 1.8344zm-8.3502-3.5023c-.095-.2699-.3829-.5475-.7503-.5557-.3663.0083-.6542.2858-.749.5551l-1.3455 3.5415c-.1708.5305-.0217.7272.1333.7988a.8568.8568 0 0 0 .3576.0776c.2346 0 .4139-.0952.4678-.2481l.2787-.7297 1.7152.0001.2785.7292c.0541.1532.2335.2484.4681.2484a.8601.8601 0 0 0 .3576-.0775c.1551-.0713.3041-.2681.1329-.7999l-1.3449-3.5398zm-1.3116 2.4433l.5618-1.5961.5618 1.5961H9.3757zm5.9056 1.3836c0 .2843-.2418.5156-.5391.5156h-1.8047c-.2973 0-.5391-.2314-.5391-.5156V9.3281c0-.3102.2576-.5625.5742-.5625s.5742.2523.5742.5625v3.3047h1.1953c.2974 0 .5392.2314.5392.5156z"/>
        </svg>
        <span>Continue with Kakao</span>
    </a>
</div>

<div class="flex w-full my-5 items-center">
    <div class="h-px w-full bg-gray-300"></div>
    <span class="text-gray-500 mx-3">or</span>
    <div class="h-px w-full bg-gray-300"></div>
</div>