config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/upload", views.UploadPhotoView.as_view(), name="upload"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.search, name="search"),
]

templates/mixins/edit-data.html
<form method="POST" class="w-72" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <div>
            {% for error in form.non_field_errors %}
                <span class="text-red-700 font-medium text-sm">{{error}}</span> 
            {% endfor %}
        </div>
    {% endif %}

    {% for field in form %}
        <span class="text-gray-500">{{field.label | title}}</span>
        <div class="input mb-1 {% if field.errors %}has_error{% endif %}">
            {{field}}
        </div>
        {% if field.errors %}
            {% for error in field.errors %}
                <span class="text-red-700 font-medium text-sm">{{error}}</span> 
            {% endfor %}
        {% endif %}
    {% endfor %}

    <button class="btn bg-airbnb-pink text-white mt-5">{{cta}}</button>
</form>

templates/mixins/profile-avatar.html
{% if user.avatar %}
    <div class="{{width}} {{height}} rounded-full bg-cover bg-center" style="background-image: url({{user.avatar.url}})">
{% else %}
    <div class="{{width}} {{height}} rounded-full bg-gray-500 flex justify-center items-center">
        <span class="text-white {{size}} font-bold">{{user.first_name | first}}</span>
{% endif %}
    </div>

templates/mixins/room_card.html
<a class="w-full" href="{% url 'rooms:detail' room.pk %}">
    <div class="w-full h-48 bg-cover bg-center rounded-xl" style="background-image:url({{room.get_first_photo}});"></div>
    <div class="mt-1">
        <div class="flex justify-between items-center">
            <div class="flex items-center">
                {% if room.host.superhost %}
                    <span class="uppercase border-black border-2 py-px px-1 rounded-lg font-bold text-xs mr-1">superhost</span>
                {% endif %}
                <span class="text-sm text-gray-500">{{room.city}}</span>
            </div>
            <div class="flex items-center">
                <i class="fas fa-star mr-1 text-airbnb-pink"></i>
                <span>{{room.total_rating}}</span>
            </div>
        </div>
        <div>
            <span class="text-medium text-black">{{room.name}}</span>
        </div>
    </div>
</a>