config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/upload", views.UploadPhotoView.as_view(), name="upload"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.search, name="search"),
]

rooms/models.py
from django.db import models
from django_countries.fields import CountryField
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item Model Definition"""

    name = models.CharField(max_length=140)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """Room Type Model Definition"""

    class Meta:
        verbose_name = "Room Type"


class Amenity(AbstractItem):

    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):

    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """Room Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField()
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = self.city.title()
        super().save(*args, **kwargs)

    def total_rating(self):
        all_reviews = self.reviews.all()
        if len(all_reviews) > 0:
            total = 0
            for review in all_reviews:
                total += review.average_rating()
            return round(total / len(all_reviews), 2)
        else:
            return 0

    def get_first_photo(self):
        (first_photo) = self.photos.all()[0]
        return first_photo.file.url

    def get_next_four_photo(self):
        photos = self.photos.all()[1:5]
        return photos

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from rooms import models as room_models
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, queryset=room_models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=room_models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=room_models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )


class UploadPhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("file", "caption")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
from django.http import Http404
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView, UpdateView, FormView
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from users import mixins as user_mixins
from . import models, forms


class HomeView(ListView):

    model = models.Room
    page_kwarg = "p"
    paginate_by = 12
    paginate_orphans = 5
    context_object_name = "rooms"
    template_name = "home.html"


class RoomDetailView(DetailView):

    model = models.Room
    template_name = "rooms/detail.html"


def search(request):

    city = request.GET.get("city")
    rooms = None

    if city:
        form = forms.SearchForm(request.GET)

        if form.is_valid():
            city = form.cleaned_data.get("city")
            country = form.cleaned_data.get("country")
            room_type = form.cleaned_data.get("room_type")
            price = form.cleaned_data.get("price")
            guests = form.cleaned_data.get("guests")
            bedrooms = form.cleaned_data.get("bedrooms")
            beds = form.cleaned_data.get("beds")
            baths = form.cleaned_data.get("baths")
            instant_book = form.cleaned_data.get("instant_book")
            superhost = form.cleaned_data.get("superhost")
            amenities = form.cleaned_data.get("amenities")
            facilities = form.cleaned_data.get("facilities")

            filter_args = {}

            if city != "Anywhere":
                filter_args["city__startswith"] = city

            filter_args["country"] = country

            if room_type is not None:
                filter_args["room_type"] = room_type

            if price is not None:
                filter_args["price__lte"] = price

            if guests is not None:
                filter_args["guests__gte"] = guests

            if bedrooms is not None:
                filter_args["bedrooms__gte"] = bedrooms

            if beds is not None:
                filter_args["beds__gte"] = beds

            if baths is not None:
                filter_args["baths__gte"] = baths

            if instant_book is True:
                filter_args["instant_book"] = True

            if superhost is True:
                filter_args["host__superhost"] = True

            rooms = models.Room.objects.filter(**filter_args)

            for amenity in amenities:
                rooms = rooms.filter(amenities=amenity)

            for facility in facilities:
                rooms = rooms.filter(facilities=facility)

    else:

        form = forms.SearchForm()

    return render(request, "rooms/search.html", context={"form": form, "rooms": rooms})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):

    model = models.Room
    template_name = "rooms/edit-room.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

    model = models.Room
    template_name = "rooms/room-photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user

    try:
        room = models.Room.objects.get(pk=room_pk)
        photo = models.Photo.objects.get(pk=photo_pk)
        if room.host.pk != user.pk or room.pk != photo.room.pk:
            messages.error(request, "Can't delete the photo")
        else:
            photo.delete()
            messages.success(request, "Photo Deleted")
        return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.LoggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/edit-photo.html"
    pk_url_kwarg = "photo_pk"
    fields = ("caption",)
    success_message = "Photo Caption Updated"

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class UploadPhotoView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/upload-photo.html"
    form_class = forms.UploadPhotoForm

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.LoggedInOnlyView, FormView):

    template_name = "rooms/create-room.html"
    form_class = forms.CreateRoomForm

    def form_valid(self, form):
        room = form.save()
        user = self.request.user
        room.host = user
        room.save()
        form.save_m2m()
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/create-room.html
{% extends 'base.html' %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/edit-data.html' with form=form cta="Create" %}

        </div>

    </div>

{% endblock content %}

templates/rooms/detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{room.name}}
{% endblock page_title %}

{% block content %}
   
    <div class="container side-padding">

        <div class="w-full h-50vh grid grid-cols-4 grid-rows-2 gap-0.5 ">
            <div class="bg-cover bg-center col-start-1 col-end-3 row-start-1 row-end-3" style="background-image:url({{room.get_first_photo}})"></div>

            {% for photo in room.get_next_four_photo %}
                <div class="bg-cover bg-center" style="background-image:url({{photo.file.url}})"></div>
            {% endfor %}
                
        </div>

   
        <div class="px-40 mt-10 flex">
            <div class="w-2/3 flex flex-col mr-10">
                <div class="w-full flex items-center justify-between">
                    <div>
                        <h4 class="font-bold text-3xl mb-2">{{room.name}}</h4>
                        <span>{{room.city}}</span>
                        
                    </div>
                    <a href="{{room.host.get_absolute_url}}" class="flex flex-col items-center">

                        {% include 'mixins/profile-avatar.html' with user=room.host width="w-16" height="h-16" size="text-2xl" %}
                        <div class="mt-2">
                            <span class="text-gray-500 ">{{room.host.username}}</span>
                            {% if room.host.superhost %}
                                <i class="fa-solid fa-circle-check text-airbnb-green"></i>
                            {% endif %}
                        </div>
                    
                    </a>
                </div>
                <div class="mt-10 border-section">
                    <span class="mr-3 text-gray-500">{{room.room_type}}</span>
                    <span class="mr-3 text-gray-500">{{room.guests}} guest{{room.guests | pluralize}}</span>
                    <span class="mr-3 text-gray-500">{{room.beds}} bed{{room.beds | pluralize}}</span>
                    <span class="mr-3 text-gray-500">{{room.bedrooms}} bedroom{{room.bedrooms | pluralize}}</span>
                    <span class="mr-3 text-gray-500">{{room.baths}} bath{{room.baths | pluralize}}</span>
                </div>
                <p class="border-section text-lg">
                    {{room.description}}
                </p>
                <div class="border-section">
                    <h2 class="font-bold mb-5">Amenities</h2>

                    {% for a in room.amenities.all %}
                        <li class="text-gray-500 mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                 <div class="border-section">
                    <h2 class="font-bold mb-5">Facilities</h2>
                    
                    {% for a in room.facilities.all %}
                        <li class="text-gray-500 mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                 <div class="border-section">
                    <h2 class="font-bold mb-5">House Rules</h2>
                    
                    {% for a in room.house_rules.all %}
                        <li class="text-gray-500 mb-2">{{a}}</li>
                    {% endfor %}
                </div>
                <div class="border-section">
                    <h4 class="font-bold text-2xl mb-5">Reviews</h4>
                    <div class="flex items-center">
                        <div class="text-lg flex items-center">
                            <i class="fas fa-star text-airbnb-pink mr-1"></i>
                            <span class="text-2xl font-bold">{{room.total_rating}}</span>
                        </div>
                        <span class="text-gray-300 mx-5">|</span>
                        <div class="flex items-center">
                            <span class="text-2xl font-bold mr-2">{{room.reviews.count}}</span>
                            <span class="text-lg">review{{room.reviews.count | pluralize}}</span>
                        </div>
                    </div>
                </div>
                <div class="flex flex-col">
                        
                        {% for review in room.reviews.all %}
                            <div class="border-section">
                                <a href="{{review.user.get_absolute_url}}" class="flex items-center mb-2">
                                    <div class="mr-3">
                                        {% include 'mixins/profile-avatar.html' with user=review.user width="w-10" height="h-10" size="text-xl" %}
                                    </div>
                                    <div class="flex flex-col">
                                        <span class="text-lg">{{review.user.username}}</span>
                                        <span class="text-sm text-gray-500">{{review.created}}</span>
                                    </div>
                                </a>
                                <p class="text-lg">{{review.review}}</p>
                            </div>
                        {% endfor %}
                            
                    </div>
            </div>

            <div class="w-1/3">
                
                {% if room.host == user %}
                    <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
                {% endif %}
                    
            
            </div>
        </div>
   
   </div>

{% endblock content %}

templates/rooms/edit-photo.html
{% extends 'base.html' %}

{% block page_title %}
    Update Photo
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/edit-data.html' with form=form cta="Update Caption" %}

        </div>

    </div>

{% endblock content %}

templates/rooms/edit-photos.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="px-80">

        {% for photo in room.photos.all %}
            <div class="border border-gray-300 py-5 px-5 flex items-center justify-between mb-5">
                <div class="flex">
                    <img src="{{photo.file.url}}" class="w-32 mr-5">
                    <span>{{photo.caption}}</span>
                </div>
                <div class="flex flex-col">
                    <a href="#" class="btn-link text-green-400 border-green-400 mb-3">Edit</a>
                    <a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="btn-link text-red-600 border-red-600">Delete</a>
                </div>
            </div>
        {% endfor %}

    </div>

{% endblock content %}

templates/rooms/edit-room.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/edit-data.html' with form=form cta="Update Room" %}

            <a href="{% url 'rooms:photos' room.pk %}" class="link mt-5">Edit Photos</a>
            
        </div>

    </div>

{% endblock content %}

templates/rooms/room-photos.html
{% extends 'base.html' %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="px-80">

        <a href="{% url 'rooms:upload' room.pk %}" class="btn-link">Upload Photo</a>

        <div class="mt-10">
            {% for photo in room.photos.all %}
                <div class="border border-gray-300 py-5 px-5 flex items-center justify-between mb-5">
                    <div class="flex">
                        <img src="{{photo.file.url}}" class="w-32 mr-5">
                        <span>{{photo.caption}}</span>
                    </div>
                    <div class="flex flex-col">
                        <a href="{% url 'rooms:edit-photo' room.pk photo.pk %}" class="btn-link text-green-400 border-green-400 mb-3">Edit</a>
                        <a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="btn-link text-red-600 border-red-600">Delete</a>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block page_title %}
    Search
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}
    <h1>Search!</h1>

    <form action="{% url 'rooms:search' %}">
        {{form.as_p}}
        <button>Search</button>
    </form>
    <hr />
    
    {% if rooms %}
    <h2>Results</h2>
    <ul>
        {% for room in rooms %}
            <li>
                <a href="{% url 'rooms:detail' room.pk %}">{{room.name}}</a>
            </li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock content %}
    

templates/rooms/upload-photo.html
{% extends 'base.html' %}

{% block page_title %}
    Upload Photo
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/edit-data.html' with form=form cta="Upload" %}

        </div>

    </div>

{% endblock content %}