config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update-profile"),
    path(
        "update-password/", views.UpdatePasswordView.as_view(), name="update-password"
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.shortcuts import reverse


class User(AbstractUser):

    """Custom User Model"""

    GENDER_MALE = "male"
    GENDER_FEMALE = "female"
    GENDER_OHTER = "other"

    GENDER_CHOICES = (
        (GENDER_MALE, "Male"),
        (GENDER_FEMALE, "Female"),
        (GENDER_OHTER, "Other"),
    )

    LANGUAGE_ENGLISH = "en"
    LANGUAGE_KOREAN = "kr"

    LANGUAGE_CHOICES = (
        (LANGUAGE_ENGLISH, "English"),
        (LANGUAGE_KOREAN, "Korean"),
    )

    CURRENCY_USD = "usd"
    CURRENCY_KRW = "krw"

    CURRENCY_CHOICES = (
        (CURRENCY_USD, "USD"),
        (CURRENCY_KRW, "KRW"),
    )

    LOGIN_EMAIL = "email"
    LOGIN_GITHUB = "github"
    LOGIN_KAKAO = "kakao"

    LOGIN_CHOICES = (
        (LOGIN_EMAIL, "Email"),
        (LOGIN_GITHUB, "Github"),
        (LOGIN_KAKAO, "Kakao"),
    )

    avatar = models.ImageField(upload_to="avatars", blank=True)
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)
    bio = models.TextField(default="", blank=True)
    birthdate = models.DateField(blank=True, null=True)
    language = models.CharField(choices=LANGUAGE_CHOICES, max_length=10, blank=True)
    currency = models.CharField(choices=CURRENCY_CHOICES, max_length=10, blank=True)
    superhost = models.BooleanField(default=False)
    login_method = models.CharField(
        choices=LOGIN_CHOICES, max_length=10, default=LOGIN_EMAIL
    )

    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"pk": self.pk})

users/forms.py
from django import forms
from . import models


class LoginForm(forms.Form):

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error(None, forms.ValidationError("Wrong Password!"))
        except models.User.DoesNotExist:
            self.add_error(None, forms.ValidationError("User does not exist!"))


class SignupForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("username", "first_name", "last_name", "email")

    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput)

    def clean_password1(self):
        password = self.cleaned_data.get("password")
        password1 = self.cleaned_data.get("password1")
        if password != password1:
            raise forms.ValidationError("Password Confirmation does not match")
        else:
            return password

    def save(self):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        user.set_password(password)
        user.save()

users/views.py
import os
import requests
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.core.files.base import ContentFile
from django.views import View
from django.views.generic import FormView, DetailView, UpdateView
from django.contrib.auth.views import PasswordChangeView
from . import forms, models, mixins


class LoginView(mixins.LoggedOutOnlyView, View):
    def get(self, request):
        form = forms.LoginForm()
        return render(request, "users/login.html", context={"form": form})

    def post(self, request):
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Welcome, {user.username}")
                return redirect(reverse("core:home"))
        return render(request, "users/login.html", context={"form": form})


def logout_view(request):
    logout(request)
    messages.success(request, "Good Bye")
    return redirect(reverse("core:home"))


class SignupView(mixins.LoggedOutOnlyView, FormView):

    template_name = "users/signup.html"
    success_url = reverse_lazy("core:home")
    form_class = forms.SignupForm

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, f"Welcome, {user.username}")
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["password1"].label = "Password Confirmation"
        return form


def github_login(request):
    client_id = os.environ.get("GH_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/github/callback"
    return redirect(
        f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user"
    )


class GithubException(Exception):
    pass


def github_callback(request):
    try:
        client_id = os.environ.get("GH_ID")
        client_secret = os.environ.get("GH_SECRET")
        code = request.GET.get("code", None)
        if code is not None:
            token_request = requests.post(
                f"https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}",
                headers={"Accept": "application/json"},
            )
            token_json = token_request.json()
            error = token_json.get("error", None)
            if error is not None:
                raise GithubException("Can't get token")
            else:
                token = token_json.get("access_token")
                profile_request = requests.get(
                    "https://api.github.com/user",
                    headers={
                        "Authorization": f"token {token}",
                        "Accept": "application/json",
                    },
                )
                profile_json = profile_request.json()
                username = profile_json.get("login", None)
                if username is not None:
                    name = profile_json.get("name")
                    email = profile_json.get("email")
                    bio = profile_json.get("bio")
                    try:
                        user = models.User.objects.get(username=username)
                        if user.login_method != models.User.LOGIN_GITHUB:
                            raise GithubException(
                                f"Please try with: {user.login_method}"
                            )
                    except models.User.DoesNotExist:
                        user = models.User.objects.create(
                            username=username,
                            first_name=name,
                            email=email,
                            bio=bio,
                            login_method=models.User.LOGIN_GITHUB,
                        )
                        user.set_unusable_password()
                        user.save()
                    login(request, user)
                    messages.success(request, f"Welcome, {user.username}")
                    return redirect(reverse("core:home"))
                else:
                    raise GithubException("Can't get username from GitHub")
        else:
            raise GithubException("Can't get code for GitHub")
    except GithubException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


def kakao_login(request):
    client_id = os.environ.get("KAKAO_ID")
    redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code"
    )


class KakaoException(Exception):
    pass


def kakao_callback(request):
    try:
        code = request.GET.get("code")
        client_id = os.environ.get("KAKAO_ID")
        redirect_uri = "http://127.0.0.1:8000/users/login/kakao/callback"
        token_request = requests.get(
            f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}"
        )
        token_json = token_request.json()
        error = token_json.get("error", None)
        if error is not None:
            raise KakaoException("Can't get token")
        else:
            access_token = token_json.get("access_token")
            profile_request = requests.get(
                "https://kapi.kakao.com/v2/user/me",
                headers={"Authorization": f"Bearer {access_token}"},
            )
            profile_json = profile_request.json()
            kakao_account = profile_json.get("kakao_account", None)
            if kakao_account is None:
                raise KakaoException("Can't get info from Kakao")
            email = kakao_account.get("email")
            profile_image = kakao_account.get("profile").get("profile_image_url")
            nickname = kakao_account.get("profile").get("nickname")
            try:
                user = models.User.objects.get(username=email)
                if user.login_method != models.User.LOGIN_KAKAO:
                    raise KakaoException(f"Please try with: {user.login_method}")
            except models.User.DoesNotExist:
                user = models.User.objects.create(
                    username=email,
                    first_name=nickname,
                    email=email,
                    login_method=models.User.LOGIN_KAKAO,
                )
                user.set_unusable_password()
                user.save()
                if profile_image is not None:
                    photo_request = requests.get(profile_image)
                    user.avatar.save(
                        f"{nickname}-avatar", ContentFile(photo_request.content)
                    )
            login(request, user)
            messages.success(request, f"Welcome, {user.username}")
            return redirect(reverse("core:home"))
    except KakaoException as e:
        messages.error(request, e)
        return redirect(reverse("users:login"))


class ProfileView(DetailView):

    model = models.User
    context_object_name = "user_obj"


class UpdateProfileView(mixins.LoggedInOnlyView, UpdateView):

    model = models.User
    template_name = "users/update-profile.html"
    fields = (
        "first_name",
        "last_name",
        "username",
        "email",
        "avatar",
        "gender",
        "bio",
        "birthdate",
        "language",
        "currency",
    )

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return self.request.user.get_absolute_url()


class UpdatePasswordView(
    mixins.EmailLoginOnlyView, mixins.LoggedInOnlyView, PasswordChangeView
):

    template_name = "users/update-password.html"

    def get_success_url(self):
        return self.request.user.get_absolute_url()

templates/users/login.html
{% extends 'base.html' %}

{% block page_title %}
    Log In
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">
        
            {% include 'partials/social_login.html' %}

            {% csrf_token %}

            {% include 'mixins/edit-data.html' with form=form cta="Log In" %}

            <div class="mt-5">
                <span>Don't have an account?</span>
                <a href="{% url 'users:signup' %}" class="link">Sign Up</a>
            </div>

        </div>
    
    </div>

{% endblock content %}

templates/users/signup.html
{% extends 'base.html' %}

{% block page_title %}
    Sign Up
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'partials/social_login.html' %}

            {% include 'mixins/edit-data.html' with form=form cta="Sign Up" %}

            <div class="mt-5">
                <span>Have an account?</span>
                <a href="{% url 'users:login' %}" class="link">Log In</a>
            </div>

        </div>

    </div>

{% endblock content %}

templates/users/update-password.html
{% extends 'base.html' %}

{% block page_title %}
    Update Password
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/edit-data.html' with form=form cta="Change Password" %}

        </div>

    </div>

{% endblock content %}

templates/users/update-profile.html
{% extends 'base.html' %}

{% block page_title %}
    Update Profile
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/edit-data.html' with form=form cta="Update Profile" %}

            {% if object.login_method == "email" %}
                <div class="mt-5">
                    <a href="{% url 'users:update-password' %}" class="btn-link">Change Password</a>
                </div>
            {% endif %}

        </div>

    </div>

{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}

{% block page_title %}
    {{user_obj.username}}'s Profile
{% endblock page_title %}

{% block search_bar %}
{% endblock search_bar %}
    
{% block content %}

    <div class="side-padding">

        <div class="border border-gray-300 py-10 flex flex-col items-center justify-center">

            {% include 'mixins/profile-avatar.html' with user=user_obj width="w-28" height="h-28" size="text-5xl" %}
        
            <div class="flex items-center mt-4">
                <span class="text-3xl">{{user_obj.last_name}}, {{user_obj.first_name}}</span>
                {% if user_obj.superhost %}
                    <i class="fa-solid fa-circle-check text-airbnb-green ml-1"></i>
                {% endif %}
            </div>

            <div class="mt-3 text-gray-400 text-lg">{{user_obj.bio}}</div>
            
            {% if user == user_obj %}
                <a href="{% url 'users:update-profile' %}" class="btn-link mt-5">Edit Profile</a>
            {% endif %}

        </div>

        <div class="py-10 flex flex-col items-center justify-center">

            <h3 class="text-3xl">{{user_obj}}'s Rooms ({{user_obj.rooms.count}})</h3>

            {% if user_obj.rooms.count %}
                <div class="container mx-auto grid grid-cols-4 gap-x-5 gap-y-10 side-padding mt-20">
                    {% for room in user_obj.rooms.all %}
                        {% include 'mixins/room_card.html' with room=room %}
                    {% endfor %}
                </div>
            {% else %}
                <span class="mt-20">No Rooms Registered</span>
            {% endif %}

        </div>

    </div>

{% endblock content %}